# Entrenamiento de los agentes basados en redes neuronales

Para entrenar a los agentes, deberemos definir un set de datos con estados del juego y un set de etiquetas con la acción preferida (representada en un vector de largo 5 con ceros en todas las posiciones excepto la de la acción elegida).

Luego, entrenaremos la red neuronal en este set de datos y la guardaremos en un archivo (``NN[Agent].h5``), el cual podrá ser accedido por el agente en el archivo ``neural.py``.

In [2]:
# Librerías utilizadas para trabajar en el notebook
import tensorflow as tf # Instalar mediante pip install tensorflow
import numpy as np
import random
import os

In [3]:
# Funciones auxiliares (que pueden resultar útiles) y rival de baseline, entregado con la tarea
from agents.baseline import BaseCat, BaseMouse
from utils import bfs_search, get_valid_moves

In [4]:
# Cargamos el mapa de juego, para poder buscar espacios libres dentro de él
lab_map = np.load(os.path.join("game_map.npy"))

In [36]:
# Obtenemos los espacios libres dentro del mapa
free_positions = []

for x in range(lab_map.shape[0]):
    for y in range(lab_map.shape[1]):
        if lab_map[x, y] == 0:
            free_positions.append((x, y))

len(free_positions)

81

## Entrenamiento del gato 🐈

### Creación del set de datos

Generaremos un set de datos ``X`` que contendrá numpy arrays con la posición del gato y el ratón ``(cat_pos[0], cat_pos[1], mouse_pos[0], mouse_pos[1])``.

Además, generaremos un set de etiquetas ``y`` que contendrá numpy arrays con el movimiento a realizar (ej. ``(0, 0, 1, 0, 0)`` significa hacer el movimiento 2).

La forma en que calculas qué acción llevar a cabo dado el estado de juego es tu decisión, puede ser una búsqueda utilizando el algoritmo de BFS entregado, una política manual o una serie de reglas if-else. Lo importante es que este será el comportamiento que la red neuronal del agente tratará de aproximar. Recuerda que dispones del mapa de juego en ``lab_map`` y de un agente contra el que entrenar bajo la clase `BaseMouse`.

In [52]:
# Instanciamos al jugador oponente
rival = BaseMouse((0, 0))

# Trabajaremos a X e y como listas, en la siguiente celda las transformaremos a un array de numpy
# (los componentes que colocas en ellas si deben ser numpy arrays)
X = []
y = []

# Para cada combinación de posiciones de gato y ratón
for cat_pos in free_positions:
    for mouse_pos in free_positions:
        X.append(np.array([cat_pos[0], cat_pos[1], mouse_pos[0], mouse_pos[1]]))

        # ===== COMPLETAR =====
        # Se debe calcular un vector de accion, correspondiente a la decisión a tomar para añadirlo a la lista y
        label = np.zeros((5))   # Actualmente se trata de un vector de solo ceros, se debe reemplazar la posición del movimiento elegido por un 1
        
        dist = bfs_search(lab_map, cat_pos, mouse_pos)
        valid_moves = get_valid_moves(lab_map, cat_pos)
        if len(dist) > 1:
            move = [dist[1].x - cat_pos[0] ,dist[1].y - cat_pos[1]]
            
            if move[0] == 0 and move[1] == -1:
                index = 0
                if index in valid_moves:
                    label[index] = 1
            elif move[0] == 0 and move[1] == 1:
                index = 1
                if index in valid_moves:
                    label[index] = 1
            elif move[0] == -1 and move[1] == 0:
                index = 2
                if index in valid_moves:
                    label[index] = 1
            elif move[0] == 1 and move[1] == 0:
                index = 3
                if index in valid_moves:
                    label[index] = 1
            else:
                index = 4
                if index in valid_moves:
                    label[index] = 1
        
        y.append(label)
        print(label)


[0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0

In [53]:
# Transformamos las listas a numpy arrays
X = np.array(X)
y = np.array(y)
print(X.shape)

(6561, 4)


### Diseño y entrenamiento de la Red Neuronal

Para entrenar nuestra red neuronal, utilizaremos la librería de [`TensorFlow`](https://www.tensorflow.org/api_docs/python/tf/all_symbols), podemos instalar esta librería mediante la línea `pip install tensorflow`.

TensorFlow es una librería desarrollada por Google que nos permite construir, entrenar e implementar modelos de aprendizaje profundo en Python.

Para esto, TensorFlow nos permite armar una red en forma de "capas", [en el siguiente link encontrarás un tutorial más en detalle de cómo crear un modelo de TensorFlow](https://towardsdatascience.com/building-our-first-neural-network-in-keras-bdc8abbc17f5). Deberemos introducir todas las capas de nuestra red dentro de un objeto `tf.keras.Sequential()`, que recibe de parámetro una lista con todos los elementos de nuestra red.

<br>

A continuación se enumeran los tres principales elementos que utilizaremos en nuestro modelo:
- `tf.keras.Input(shape = a)`: La capa de entrada de la red, es la primera que recibe. Necesita de un parámetro `shape` que determinará la dimensionalidad del vector de entrada, esto será entregado en una tupla `a` (ej. `(5, 2)`).

- `tf.keras.layers.Dense(units = b, activation = 'relu')`: Corresponde a una capa intermedia de la red del tipo *Fully Connected*, le entregaremos un parámetro `units` que determinará cuántas unidades ocultas (neuronas) tendrá la capa (y por tanto, el número de componentes en el vector de salida de la capa, en este caso `b`). Además, recibirá una función de activación para cada neurona, esta puede ser del tipo `relu`, `tanh`, `softmax` u otras, para más detalle sobre ellas visitar [el siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/activations). Recomendamos usar `relu` para capas intermedias.

- `tf.keras.layers.Dense(units = c, activation = 'softmax')`: Similar a lo explicado anteriormente, corresponde a una capa densa de activación `softmax`. Esta corresponderá a la capa final del modelo, con `c` el número de elementos que deseamos que nuestro vector de salida tenga. El uso de una función softmax se debe a que esta nos permite llevar la salida de nuestra neurona a un conjunto de probabilidades normalizadas, desde el cual podemos calcular qué acción jugar. [En el siguiente link](https://deepai.org/machine-learning-glossary-and-terms/softmax-layer) se explica el funcionamiento de esta función en mayor detalle.

<br>

Un ejemplo de una red simple sería:
```
model = tf.keras.Sequential([
    tf.keras.Input(shape = a),
    tf.keras.layers.Dense(b, activation = "relu"),
    tf.keras.layers.Dense(c, activation = "softmax")
])
```

In [77]:
# Recuerda que para esta tarea la entrada es un vector de 4 elementos y buscamos una salida de 5 elementos (la probabilidad de jugar acción posible)

# ===== COMPLETAR =====
# Se debe crear un modelo para nuestra red neuronal, añade cuantas capas ocultas desees, con cuantas neuronas desees
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(4,)),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])
# =====================

TensorFlow nos permite además compilar un modelo, especificando qué optimizador utilizar para su ajuste de parámetros y qué función de pérdida utilizar para hacer la backpropagation.

Compilaremos un modelo de la forma:
``model.compile(optimizer = 'optimizer_name', loss = 'loss_name', metrics = ['accuracy'])``

- Con `optimizer_name` el nombre de algún optimizador (por ejemplo, `sgd` o `adam`, más optimizadores en el [siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers))
- Con `loss_name` el nombre de alguna función de pérdida (por ejemplo, `binary_crossentropy`, más funciones en el [siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/losses))
- Usaremos de métrica el accuracy del modelo, aunque existe [múltiples otras métricas que incluir](https://www.tensorflow.org/api_docs/python/tf/keras/metrics)

In [78]:
# ===== COMPLETAR =====
# Compila tu modelo de TensorFlow
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])
# =====================


Ahora que especificamos cómo vamos calcular el error del modelo y cómo lo usaremos para ajustar sus pesos, es hora de entrenar nuestra red. Para ello, utilizaremos su método `.fit()` de la siguiente forma:

`model.fit(X, y, epochs = a, batch_size = b)`

- `X` corresponde a nuestra matriz de características
- `y` corresponde a nuestro vector de etiquetas para cada muestra
- `epochs` determina cuántas veces iteraremos sobre todo el set de datos
- `batch_size` determina cuántas muestras serán consideradas por propagación del gradiente (un valor mayor significa entrenamiento más rápido pero mayor uso de memoria)

In [82]:
# ===== COMPLETAR =====
# Entrena tu modelo de TensorFlow utilizando su método .fit()
model.fit(X, y, epochs=1000, batch_size=64)
# =====================

Epoch 1/1000
103/103 [==============================] - 0s 913us/step - loss: 0.0045 - accuracy: 0.9869
Epoch 2/1000
103/103 [==============================] - 0s 814us/step - loss: 0.0032 - accuracy: 0.9883
Epoch 3/1000
103/103 [==============================] - 0s 1ms/step - loss: 0.0023 - accuracy: 0.9883
Epoch 4/1000
103/103 [==============================] - 0s 840us/step - loss: 0.0036 - accuracy: 0.9872
Epoch 5/1000
103/103 [==============================] - 0s 799us/step - loss: 0.0050 - accuracy: 0.9861
Epoch 6/1000
103/103 [==============================] - 0s 809us/step - loss: 0.0127 - accuracy: 0.9816
Epoch 7/1000
103/103 [==============================] - 0s 786us/step - loss: 0.0310 - accuracy: 0.9736
Epoch 8/1000
103/103 [==============================] - 0s 824us/step - loss: 0.0254 - accuracy: 0.9755
Epoch 9/1000
103/103 [==============================] - 0s 834us/step - loss: 0.0080 - accuracy: 0.9851
Epoch 10/1000
103/103 [==============================] - 0s 794us/

Por último, guardaremos el modelo entrenado en el directorio `agents/data/NNCat.h5` para poder acceder a este modelo desde nuestra clase `NNCat`:

In [83]:
model.save(os.path.join('agents', 'data', 'NNCat.h5'))

## Entrenamiento del ratón 🐁

### Creación del set de datos

Generaremos un set de datos ``X`` que contendrá numpy arrays con la posición del gato y el ratón ``(cat_pos[0], cat_pos[1], mouse_pos[0], mouse_pos[1])``.

Además, generaremos un set de etiquetas ``y`` que contendrá numpy arrays con el movimiento a realizar (ej. ``(1, 0, 0, 0, 0)`` significa hacer el movimiento 0).

La forma en que calculas qué acción llevar a cabo dado el estado de juego es tu decisión. Lo importante es que este será el comportamiento que la red neuronal del agente tratará de aproximar. Recuerda que dispones del mapa de juego en ``lab_map`` y de un agente contra el que entrenar bajo la clase `BaseCat`.

In [101]:
# Instanciamos al jugador oponente
rival = BaseCat((0, 0))

X = []
y = []
for cat_pos in free_positions:
    for mouse_pos in free_positions:
        X.append(np.array([cat_pos[0], cat_pos[1], mouse_pos[0], mouse_pos[1]]))

        label = np.zeros((5))   
        if cat_pos != mouse_pos:
            valid_moves = get_valid_moves(lab_map, mouse_pos)

            distances = []
            for move in valid_moves:
                # Calculate the next position of the mouse for each valid move
                if move == 0:
                    next_pos = mouse_pos[0], mouse_pos[1] - 1
                elif move == 1:
                    next_pos = mouse_pos[0], mouse_pos[1] + 1
                elif move == 2:
                    next_pos = mouse_pos[0] - 1, mouse_pos[1]
                elif move == 3:
                    next_pos = mouse_pos[0] + 1, mouse_pos[1]
                else:
                    next_pos = mouse_pos[0], mouse_pos[1]

                # Calculate the distance between the next position and the cat's position
                distance = np.sqrt((next_pos[0] - cat_pos[0])**2 + (next_pos[1] - cat_pos[1])**2)
                distances.append(distance)

            best_move = valid_moves[np.argmax(distances)]
            label[best_move] = 1
        else:
            label[4] = 1
        y.append(label)
        # print(label)


In [103]:
# Transformamos las listas a numpy arrays
X = np.array(X)
y = np.array(y)


(6561, 5)


### Diseño y entrenamiento de la Red Neuronal

Para entrenar nuestra red neuronal, utilizaremos la librería de [`TensorFlow`](https://www.tensorflow.org/api_docs/python/tf/all_symbols), podemos instalar esta librería mediante la línea `pip install tensorflow`.

TensorFlow es una librería desarrollada por Google que nos permite construir, entrenar e implementar modelos de aprendizaje profundo en Python.

Para esto, TensorFlow nos permite armar una red en forma de "capas", [en el siguiente link encontrarás un tutorial más en detalle de cómo crear un modelo de TensorFlow](https://towardsdatascience.com/building-our-first-neural-network-in-keras-bdc8abbc17f5). Deberemos introducir todas las capas de nuestra red dentro de un objeto `tf.keras.Sequential()`, que recibe de parámetro una lista con todos los elementos de nuestra red.

<br>

A continuación se enumeran los tres principales elementos que utilizaremos en nuestro modelo:
- `tf.keras.Input(shape = a)`: La capa de entrada de la red, es la primera que recibe. Necesita de un parámetro `shape` que determinará la dimensionalidad del vector de entrada, esto será entregado en una tupla `a` (ej. `(5, 2)`).

- `tf.keras.layers.Dense(units = b, activation = 'relu')`: Corresponde a una capa intermedia de la red del tipo *Fully Connected*, le entregaremos un parámetro `units` que determinará cuántas unidades ocultas (neuronas) tendrá la capa (y por tanto, el número de componentes en el vector de salida de la capa, en este caso `b`). Además, recibirá una función de activación para cada neurona, esta puede ser del tipo `relu`, `tanh`, `softmax` u otras, para más detalle sobre ellas visitar [el siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/activations). Recomendamos usar `relu` para capas intermedias.

- `tf.keras.layers.Dense(units = c, activation = 'softmax')`: Similar a lo explicado anteriormente, corresponde a una capa densa de activación `softmax`. Esta corresponderá a la capa final del modelo, con `c` el número de elementos que deseamos que nuestro vector de salida tenga. El uso de una función softmax se debe a que esta nos permite llevar la salida de nuestra neurona a un conjunto de probabilidades normalizadas, desde el cual podemos calcular qué acción jugar. [En el siguiente link](https://deepai.org/machine-learning-glossary-and-terms/softmax-layer) se explica el funcionamiento de esta función en mayor detalle.

<br>

Un ejemplo de una red simple sería:
```
model = tf.keras.Sequential([
    tf.keras.Input(shape = a),
    tf.keras.layers.Dense(b, activation = "relu"),
    tf.keras.layers.Dense(c, activation = "softmax")
])
```

In [104]:
# Recuerda que para esta tarea la entrada es un vector de 4 elementos y buscamos una salida de 5 elementos (la probabilidad de jugar acción posible)

# ===== COMPLETAR =====
# Se debe crear un modelo para nuestra red neuronal, añade cuantas capas ocultas desees, con cuantas neuronas desees
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(4,)),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])
# =====================

TensorFlow nos permite además compilar un modelo, especificando qué optimizador utilizar para su ajuste de parámetros y qué función de pérdida utilizar para hacer la backpropagation.

Compilaremos un modelo de la forma:
``model.compile(optimizer = 'optimizer_name', loss = 'loss_name', metrics = ['accuracy'])``

- Con `optimizer_name` el nombre de algún optimizador (por ejemplo, `sgd` o `adam`, más optimizadores en el [siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers))
- Con `loss_name` el nombre de alguna función de pérdida (por ejemplo, `binary_crossentropy`, más funciones en el [siguiente link](https://www.tensorflow.org/api_docs/python/tf/keras/losses))
- Usaremos de métrica el accuracy del modelo, aunque existe [múltiples otras métricas que incluir](https://www.tensorflow.org/api_docs/python/tf/keras/metrics)

In [105]:
# ===== COMPLETAR =====
# Compila tu modelo de TensorFlow
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])
# =====================

Ahora que especificamos cómo vamos calcular el error del modelo y cómo lo usaremos para ajustar sus pesos, es hora de entrenar nuestra red. Para ello, utilizaremos su método `.fit()` de la siguiente forma:

`model.fit(X, y, epochs = a, batch_size = b)`

- `X` corresponde a nuestra matriz de características
- `y` corresponde a nuestro vector de etiquetas para cada muestra
- `epochs` determina cuántas veces iteraremos sobre todo el set de datos
- `batch_size` determina cuántas muestras serán consideradas por propagación del gradiente (un valor mayor significa entrenamiento más rápido pero mayor uso de memoria)

In [106]:
# ===== COMPLETAR =====
# Entrena tu modelo de TensorFlow utilizando su método .fit()
model.fit(X, y, epochs=1000, batch_size=64)
# =====================

Epoch 1/1000
103/103 [==============================] - 1s 911us/step - loss: 0.4246 - accuracy: 0.4598
Epoch 2/1000
103/103 [==============================] - 0s 829us/step - loss: 0.3661 - accuracy: 0.5263
Epoch 3/1000
103/103 [==============================] - 0s 830us/step - loss: 0.3426 - accuracy: 0.5670
Epoch 4/1000
103/103 [==============================] - 0s 976us/step - loss: 0.3254 - accuracy: 0.5848
Epoch 5/1000
103/103 [==============================] - 0s 832us/step - loss: 0.3124 - accuracy: 0.6030
Epoch 6/1000
103/103 [==============================] - 0s 818us/step - loss: 0.3026 - accuracy: 0.6144
Epoch 7/1000
103/103 [==============================] - 0s 857us/step - loss: 0.2966 - accuracy: 0.6133
Epoch 8/1000
103/103 [==============================] - 0s 830us/step - loss: 0.2888 - accuracy: 0.6237
Epoch 9/1000
103/103 [==============================] - 0s 819us/step - loss: 0.2831 - accuracy: 0.6232
Epoch 10/1000
103/103 [==============================] - 0s 826u

Por último, guardaremos el modelo entrenado en el directorio `agents/data/NNMouse.h5` para poder acceder a este modelo desde nuestra clase `NNMouse`:

In [107]:
model.save(os.path.join('agents', 'data', 'NNMouse.h5'))

## Parte Desarrollo


 ### A)


Para este caso, era bastante simple calcular el resultado para cada posibilidad, por lo que hacer overffiting nos garantiza un funcionamiento optimo en esta, porque podemos saber perfectamente cual es la mejor opción instantaneamente. En cambio en situaciones normales es imposible poder iterar sobre todas las posibilidades, ya sea por que se necesitaría una capacidad computacional enorme, o simplemente no se encuentran todos los datos necesarios para lograr eso, en cambio se desea encontrar una solución mas general para problemas nuevos, y para eso no nos sirve el overfitting.

### B)


 Reconocimiento de imágenes: Supongamos que estamos entrenando una red neuronal para reconocer imágenes de gatos y perros. Si la red neuronal sufre de overfitting, aprenderá a clasificar muy bien las imágenes de entrenamiento específicas que ha visto, pero tendrá dificultades para generalizar y clasificar correctamente imágenes nuevas. Esto significa que la red neuronal podría sobresaturarse con características y detalles específicos de las imágenes de entrenamiento, perdiendo la capacidad de reconocer patrones más generales y, por lo tanto, fallando al clasificar correctamente nuevas imágenes de gatos y perros.

Predicción financiera: Supongamos que estamos construyendo una red neuronal para predecir los precios de las acciones en el mercado financiero. Si la red neuronal se ajusta demasiado a los datos de entrenamiento, podría aprender patrones espurios o ruidosos que no se mantienen en datos nuevos y desconocidos. Esto puede llevar a predicciones incorrectas y poco confiables cuando se utiliza la red neuronal para predecir el comportamiento futuro del mercado. En este caso, el overfitting sería perjudicial, ya que deseamos que la red neuronal capture patrones generales y útiles en lugar de ruido o peculiaridades específicas de los datos de entrenamiento.

### C)

La función softmax se utiliza para poder transformar los pesos de las neuronas de la capa de salida en valores de probabilidades para un vector de soluciones ligado a una respuesta esperada, osea sirve para poder interactuar con el resultado de la red neuronal de forma eficiente.

### D)

Mi modelo contiene 3 Capas, ademas de la capa de entrada y de salida,ademas tienen 100, 64 y 32 Neuronas cada capa respectivamente, mi idea en cuanto a los valores decrecientes, era ir reduciendo la dimensionalidad del modelo paulatinamente, mientras que en las primeras capas me enfocaba en extraer todas las caracteristicas principales con una mayor cantidad de neuronas. Llegue a estos numeros en especifico luego de varios testeos, siendo estos los que mejor resultado me dieron.